---

- name: Install Nginx On Centos
  yum:
    name: nginx
    state: present
  when: 
    - ansible_distribution == "CentOS"

- name: Install Nginx On Ubuntu
  apt:
    name: nginx
    state: present
  when: 
    - ansible_distribution == "Ubuntu"

- name: Replace nginx conf
  template:
    src: openstack.conf.j2
    dest: /etc/nginx/nginx.conf/oipenstack.conf

- name: Restart Nginx Service
  shell: |
    systemctl restart nginx
