---

- name: Get start timestamp
  hosts: deploy
  connection: local
  tasks:
    - set_fact:
        starttime: '{{ ansible_date_time }}'
  tags: info

- name: Create user test-dev
  hosts: deploy
  connection: local
  tasks:
    - os_user:
        cloud: rdenv
        state: present
        name: test-dev
        password: Rk5mSdwO83eI
        email: test-dev@advantech.com
        default_project: test
  tags: user

- name: Associate user role to test-dev
  hosts: deploy
  connection: local
  tasks:
    - os_user_role:
        cloud: rdenv
        user: test-dev
        role: user
        project: test
  tags: user

- name: Configure quota for project test
  hosts: deploy
  connection: local
  tasks:
    - os_quota:
        cloud: rdenv
        name: test
        cores: 200
        ram: 532480
        instances: 70
        gigabytes: 8192
        volumes: 40
        network: 8
        floatingip: 10
        security_group: 2
  tags: quota

- name: Inform the installer
  hosts: deploy
  connection: local
  tasks:
    - debug:
        msg: >-
          The work load started at {{ hostvars.deploy.starttime.time }},
          ended at {{ ansible_date_time.time }}
  tags: info
